### ISSUE TITLE
Add a `flake.nix`

### ISSUE THREAD

**Issue by srid** [juspay/jrec#27]
Convert the `default.nix` to a `flake.nix` such that `nix build` builds the package and `nix develop` puts us in a development shell where both `cabal build` and `haskell-language-server` commands run and succeed.

Ref:

- https://nixos.wiki/wiki/Flakes
- https://nixos.wiki/wiki/Haskell

**Comment by abshekh** [comment]
@srid changes in #26 are a requirement for adding `flake.nix`. Can we get it merged.
